@startuml
left to right direction
usecase 登录
usecase 注册
usecase 注册成为管理员
usecase 添加物品
usecase 删除物品
usecase 查询物品
usecase 展示所有物品
usecase 添加或修改物品类型和属性
usecase 批准普通用户登录
usecase 退出登录
usecase 注销账号
usecase 检查邀请码
usecase 展示给定物品列表
usecase 展示用户列表
actor 普通用户
actor 管理员用户
普通用户 --> 登录
普通用户 --> 注册
普通用户 --> 添加物品
普通用户 --> 删除物品
普通用户 --> 查询物品
普通用户 --> 退出登录
普通用户 --> 展示所有物品
普通用户 --> 注销账号
管理员用户 --> 登录
管理员用户 --> 注册成为管理员
管理员用户 --> 添加物品
管理员用户 --> 删除物品
管理员用户 --> 查询物品
管理员用户 --> 展示所有物品
管理员用户 --> 添加或修改物品类型和属性
管理员用户 --> 批准普通用户登录
管理员用户 --> 退出登录
管理员用户 --> 注销账号
添加物品 ..> 登录 : include
删除物品 .> 登录 : include
查询物品 .> 登录 : include
展示所有物品 .> 登录 : include
添加或修改物品类型和属性 ..> 登录 : include
批准普通用户登录 ..> 登录 : include
退出登录 ..> 登录 : include
注销账号 ..> 登录 : include
注册成为管理员 .> 检查邀请码 : include
添加物品 ..> 展示给定物品列表 : include
删除物品 ..> 展示给定物品列表 : include
查询物品 ..> 展示给定物品列表 : include
展示所有物品 ..> 展示给定物品列表 : include
批准普通用户登录 ..> 展示用户列表 : include
@enduml